/**
 * App Redux Action Types
 */

// Auth Actions
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const CONFIRM_USER_PINCODE = 'CONFIRM_USER_PINCODE';
export const CONFIRM_USER_PINCODE_SUCCESS = 'CONFIRM_USER_PINCODE_SUCCESS';
export const CONFIRM_USER_PINCODE_FAILURE = 'CONFIRM_USER_PINCODE_FAILURE';
export const RESET_LOGIN ="RESET_LOGIN"
export const CHECK_AUTH_STATUS="CHECK_AUTH_STATUS";
export const CHECK_AUTH_STATUS_SUCCESS="CHECK_AUTH_STATUS_SUCCESS";
export const LOGOUT_USER="LOGOUT_USER";
export const LOGOUT_USER_SUCCESS="LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE="LOGOUT_USER_FAILURE";

//settings actions
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const GET_USER_SETTINGS="GET_USER_SETTINGS";
export const GET_USER_SETTINGS_SUCCESS="GET_USER_SETTINGS_SUCCESS";

//dashboard actions
export const GET_SEGMENTS = 'GET_SEGMENTS';
export const GET_SEGMENTS_SUCCESS = 'GET_SEGMENTS_SUCCESS';
export const GET_SEGMENTS_FALIURE = 'GET_SEGMENTS_FALIURE';

export const GET_GLOBAL_SEGMENTS = 'GET_GLOBAL_SEGMENTS';
export const GET_GLOBAL_SEGMENTS_SUCCESS = 'GET_GLOBAL_SEGMENTS_SUCCESS';
export const GET_GLOBAL_SEGMENTS_FALIURE = 'GET_GLOBAL_SEGMENTS_FALIURE';


export const SAVE_SEGMENTS = 'SAVE_SEGMENTS';
export const SAVE_SEGMENTS_SUCCESS = 'SAVE_SEGMENTS_SUCCESS';
export const SAVE_SEGMENTS_FALIURE = 'SAVE_SEGMENTS_FALIURE';

export const GET_PROFILE="GET_PROFILE";
export const GET_PROFILE_SUCCESS="GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE="GET_PROFILE_FAILURE";

export const GET_USER_CONSENTS="GET_USER_CONSENTS";
export const GET_USER_CONSENTS_SUCCESS="GET_USER_CONSENTS_SUCCESS";
export const GET_USER_CONSENTS_FAILURE="GET_USER_CONSENTS_FAILURE";

export const GET_USER_EVENTS="GET_USER_EVENTS";
export const GET_USER_EVENTS_SUCCESS="GET_USER_EVENTS_SUCCESS";
export const GET_USER_EVENTS_FAILURE="GET_USER_EVENTS_FAILURE";

export const UPDATE_USER_CONSENT="UPDATE_USER_CONSENT";
export const UPDATE_USER_CONSENT_SUCCESS="UPDATE_USER_CONSENT_SUCCESS";
export const UPDATE_USER_CONSENT_FAILURE="UPDATE_USER_CONSENT_FAILURE";

export const UPDATE_USER_PROFILE="UPDATE_USER_PROFILE";
export const UPDATE_USER_PROFILE_SUCCESS="UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAILURE="UPDATE_USER_PROFILE_SUCCESS";


